//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zmedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_template
    {
        public int Id { get; set; }
        public Nullable<bool> Data_Status { get; set; }
        public Nullable<int> Number { get; set; }
        public string Prefix { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string ID_Passport { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string AGE { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Collected_Date { get; set; }
        public string Specimen { get; set; }
        public string Hospital_Clinic { get; set; }
        public string Doctor { get; set; }
        public string VN { get; set; }
        public string LN { get; set; }
        public string HN { get; set; }
        public string N_gene_Ct { get; set; }
        public string S_gene_Ct { get; set; }
        public string Date_start { get; set; }
        public string Time_Start { get; set; }
        public string Date_Finish { get; set; }
        public string Time_Finish { get; set; }
        public string Result { get; set; }
        public string MC { get; set; }
        public Nullable<System.DateTime> Received_Date { get; set; }
    }
}
