//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zmedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public Nullable<bool> Data_Status { get; set; }
        public string ID_Passport { get; set; }
        public string DOB { get; set; }
        public string LN { get; set; }
        public Nullable<System.DateTime> Collected_Date { get; set; }
        public string File_Name { get; set; }
        public Nullable<System.DateTime> Time_stamp { get; set; }
        public string MC_File_Name { get; set; }
        public string E_mail { get; set; }
    }
}
