//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zmedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public string Upload_file_name { get; set; }
        public Nullable<int> Number_of_Records { get; set; }
        public Nullable<int> Number_of_Success { get; set; }
        public Nullable<int> Number_of_Fails { get; set; }
        public string User { get; set; }
        public string Upload_Reuslt { get; set; }
    }
}
